# Generated by Django 6.0.6 on 2026-06-19 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField(blank=True)),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_enabled', models.BooleanField(default=True)),
                ('cash_description', models.CharField(default='الدفع عند استلام الطلب بعد تأكيد التوفر والسعر النهائي.', max_length=240)),
                ('sham_cash_enabled', models.BooleanField(default=True)),
                ('sham_cash_label', models.CharField(default='شام كاش', max_length=120)),
                ('sham_cash_description', models.CharField(default='يمكن الدفع عبر شام كاش بعد تأكيد الطلب عبر واتساب.', max_length=240)),
                ('sham_cash_qr', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('whatsapp_description', models.CharField(default='الاتفاق وتأكيد الطلب مباشرة عبر واتساب.', max_length=240)),
            ],
            options={
                'verbose_name': 'Payment settings',
                'verbose_name_plural': 'Payment settings',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='مول صحنايا الطبي', max_length=180)),
                ('english_name', models.CharField(default='SAHNAYA MEDICAL MALL', max_length=180)),
                ('short_name', models.CharField(default='SMM', max_length=50)),
                ('tagline', models.CharField(default='كل ما يلزم الطبيب والمريض تجده هنا', max_length=220)),
                ('whatsapp_number', models.CharField(default='+963945151299', max_length=40)),
                ('location', models.CharField(default='صحنايا', max_length=220)),
                ('address', models.TextField(blank=True)),
                ('exchange_rate', models.PositiveIntegerField(default=13000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('products_page_size', models.PositiveIntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_syp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_price_visible', models.BooleanField(default=True)),
                ('stock_status', models.CharField(choices=[('available', 'Available'), ('request', 'On request'), ('out_of_stock', 'Out of stock')], default='available', max_length=20)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('navy', 'Navy')], default='blue', max_length=20)),
                ('is_new', models.BooleanField(default=False)),
                ('is_offer', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
