# Generated by Django 6.0.6 on 2026-06-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_syp',
        ),
    ]
