# Generated by Django 5.2.15 on 2026-06-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_price_syp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان البانر')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='النص الفرعي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='صورة البانر')),
                ('link_label', models.CharField(blank=True, max_length=120, verbose_name='نص الزر')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الزر أو المسار الداخلي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'بانر عرض',
                'verbose_name_plural': 'بنرات العروض',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'شريحة رئيسية', 'verbose_name_plural': 'شرائح الواجهة الرئيسية'},
        ),
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={'verbose_name': 'إعدادات الدفع', 'verbose_name_plural': 'إعدادات الدفع'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'إعدادات الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
        migrations.AddField(
            model_name='storesettings',
            name='app_icon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='أيقونة التطبيق'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط الموقع على الخريطة'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='shipping_note',
            field=models.CharField(default='شحن لكافة المحافظات السورية', max_length=220, verbose_name='ملاحظة الشحن'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_best_sellers_section',
            field=models.BooleanField(default=True, verbose_name='إظهار قسم الأكثر طلباً'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_categories_section',
            field=models.BooleanField(default=True, verbose_name='إظهار قسم التصنيفات'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_hero_section',
            field=models.BooleanField(default=True, verbose_name='إظهار قسم الهيرو'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_new_products_section',
            field=models.BooleanField(default=True, verbose_name='إظهار قسم جديدنا'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_offers_section',
            field=models.BooleanField(default=True, verbose_name='إظهار قسم العروض'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='static_hero_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='settings/hero/', verbose_name='صورة الهيرو الثابتة للديسكتوب'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='static_hero_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='settings/hero/', verbose_name='صورة الهيرو الثابتة للجوال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=160, unique=True, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='يُنشأ تلقائياً إذا تركته فارغاً.', max_length=180, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='صورة الديسكتوب'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=120, verbose_name='النص الصغير فوق العنوان'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعلة'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='صورة الجوال'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='text',
            field=models.TextField(blank=True, verbose_name='نص الشريحة'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(max_length=220, verbose_name='عنوان الشريحة'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='cash_description',
            field=models.CharField(default='الدفع عند استلام الطلب بعد تأكيد التوفر والسعر النهائي.', max_length=240, verbose_name='وصف الدفع عند الاستلام'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='cash_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الدفع عند الاستلام'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='sham_cash_description',
            field=models.CharField(default='يمكن الدفع عبر شام كاش بعد تأكيد الطلب عبر واتساب.', max_length=240, verbose_name='وصف شام كاش'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='sham_cash_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل شام كاش'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='sham_cash_label',
            field=models.CharField(default='شام كاش', max_length=120, verbose_name='اسم طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='sham_cash_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='صورة QR شام كاش'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='whatsapp_description',
            field=models.CharField(default='الاتفاق وتأكيد الطلب مباشرة عبر واتساب.', max_length=240, verbose_name='وصف واتساب'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الطلب عبر واتساب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'أحمر'), ('blue', 'أزرق'), ('cyan', 'سماوي'), ('navy', 'كحلي')], default='blue', max_length=20, verbose_name='لون بطاقة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='الأكثر طلباً'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='جديد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False, verbose_name='عرض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_price_visible',
            field=models.BooleanField(default=True, verbose_name='إظهار السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=220, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر بالدولار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='يُنشأ تلقائياً إذا تركته فارغاً.', max_length=240, unique=True, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('available', 'متوفر'), ('request', 'عند الطلب'), ('out_of_stock', 'غير متوفر')], default='available', max_length=20, verbose_name='حالة التوفر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='english_name',
            field=models.CharField(default='SAHNAYA MEDICAL MALL', max_length=180, verbose_name='الاسم الإنكليزي'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='exchange_rate',
            field=models.PositiveIntegerField(default=13000, verbose_name='سعر صرف الدولار'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='location',
            field=models.CharField(default='صحنايا', max_length=220, verbose_name='الموقع المختصر'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='products_page_size',
            field=models.PositiveIntegerField(default=12, verbose_name='عدد المنتجات في الصفحة'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='short_name',
            field=models.CharField(default='SMM', max_length=50, verbose_name='الاسم المختصر'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='site_name',
            field=models.CharField(default='مول صحنايا الطبي', max_length=180, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='tagline',
            field=models.CharField(default='كل ما يلزم الطبيب والمريض تجده هنا', max_length=220, verbose_name='الشعار النصي'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp_number',
            field=models.CharField(default='+963945151299', max_length=40, verbose_name='رقم الواتساب'),
        ),
    ]
